omod/src/main/java/org/openmrs/module/metadatasharing/web/bean/PackageItems.java
/**
 * The contents of this file are subject to the OpenMRS Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://license.openmrs.org
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 *
 * Copyright (C) OpenMRS, LLC.  All Rights Reserved.
 */
package org.openmrs.module.metadatasharing.web.bean;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import org.openmrs.module.metadatasharing.Item;
import org.openmrs.module.metadatasharing.web.controller.ExportController;

/**
 * A session object for {@link ExportController}.
 */
public class PackageItems {
	
	private Map<String, Set<Item>> items = new HashMap<String, Set<Item>>();
	
	private Set<String> completeTypes = new HashSet<String>();
	
	/**
	 * @return the items
	 */
	public Map<String, Set<Item>> getItems() {
		return items;
	}
	
	/**
	 * @param items the items to set
	 */
	public void setItems(Map<String, Set<Item>> items) {
		this.items = items;
	}
	
	/**
	 * @return the completeTypes
	 */
	public Set<String> getCompleteTypes() {
		return completeTypes;
	}
	
	public Map<String, Boolean> getCompleteTypesMap() {
		Map<String,Boolean> map = new HashMap<String, Boolean>();
		for (String type : completeTypes) {
	        map.put(type, true);
        }
		return map;
	}
	
	/**
	 * @param completeTypes the completeTypes to set
	 */
	public void setCompleteTypes(Set<String> completeTypes) {
		this.completeTypes = completeTypes;
	}
	
}

omod/src/main/java/org/openmrs/module/metadatasharing/web/controller/ExportController.java
/**
 * The contents of this file are subject to the OpenMRS Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://license.openmrs.org
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 *
 * Copyright (C) OpenMRS, LLC.  All Rights Reserved.
 */
package org.openmrs.module.metadatasharing.web.controller;

import javax.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

import org.apache.commons.beanutils.BeanComparator;
import org.openmrs.api.context.Context;
import org.openmrs.module.metadatamapping.api.MetadataMappingService;
import org.openmrs.module.metadatasharing.ExportedPackage;
import org.openmrs.module.metadatasharing.ExportedPackageSummary;
import org.openmrs.module.metadatasharing.Item;
import org.openmrs.module.metadatasharing.MetadataSharing;
import org.openmrs.module.metadatasharing.MetadataSharingConsts;
import org.openmrs.module.metadatasharing.SerializedPackage;
import org.openmrs.module.metadatasharing.api.MetadataSharingService;
import org.openmrs.module.metadatasharing.handler.Handler;
import org.openmrs.module.metadatasharing.model.validator.PackageContainerValidator;
import org.openmrs.module.metadatasharing.publish.PublishUtils;
import org.openmrs.module.metadatasharing.task.Task;
import org.openmrs.module.metadatasharing.versioner.PackageVersioner;
import org.openmrs.module.metadatasharing.web.bean.DatatablesRequest;
import org.openmrs.module.metadatasharing.web.bean.DatatablesResponse;
import org.openmrs.module.metadatasharing.web.bean.PackageItems;
import org.openmrs.module.metadatasharing.web.utils.WebUtils;
import org.openmrs.module.metadatasharing.web.view.DownloadPackageView;
import org.openmrs.module.metadatasharing.web.view.JsonObjectView;
import org.openmrs.module.metadatasharing.wrapper.PackageExporter;
import org.openmrs.serialization.SerializationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.Errors;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.SessionAttributes;
import org.springframework.web.bind.support.SessionStatus;
import org.springframework.web.servlet.ModelAndView;

/**
 * Controller for package export pages.
 */
@Controller(MetadataSharingConsts.MODULE_ID + ".ExportController")
@SessionAttributes({ ExportController.PACKAGE_ITEMS, ExportController.EXPORTER })
public class ExportController {
	
	public static final String EXPORTER = "exporter";
	
	public static final String PACKAGE_ITEMS = "packageItems";
	
	public static final String EXPORT_PATH = MetadataSharingConsts.MODULE_PATH + "/export";
	
	public static final String LIST_PATH = EXPORT_PATH + "/list";
	
	public static final String DETAILS_PATH = EXPORT_PATH + "/details";
	
	public static final String DOWNLOAD_PATH = EXPORT_PATH + "/download";
	
	public static final String DELETE_PATH = EXPORT_PATH + "/delete";
	
	public static final String TOGGLE_PUBLISHED_PATH = EXPORT_PATH + "/togglePublished";
	
	public static final String CREATE_PATH = EXPORT_PATH + "/create";
	
	public static final String UPGRADE_PATH = EXPORT_PATH + "/upgrade";
	
	public static final String EDIT_PATH = EXPORT_PATH + "/edit";
	
	public static final String ADD_ALL_ITEMS_PATH = EXPORT_PATH + "/addAllItems";
	
	public static final String REMOVE_ALL_ITEMS_PATH = EXPORT_PATH + "/removeAllItems";
	
	public static final String SELECT_ITEMS_PATH = EXPORT_PATH + "/selectItems";
	
	public static final String JSON_ITEMS_PATH = EXPORT_PATH + "/json/items";
	
	public static final String COMPLETE_PATH = EXPORT_PATH + "/complete";
	
	@Autowired
	private PackageContainerValidator validator;
	
	@Autowired
	private DownloadPackageView downloadPackageView;
	
	@Autowired
	private JsonObjectView jsonView;
	
	@RequestMapping(LIST_PATH)
	public void list(Model model) {
		List<ExportedPackageSummary> packages = getService().getAllExportedPackageSummaries();
		Map<String, ExportedPackageSummary> latestVersion = new HashMap<String, ExportedPackageSummary>();
		// key is group
		
		Map<String, List<Integer>> publishedVersions = new HashMap<String, List<Integer>>();
		// key is group
		
		Map<String, Integer> order = new HashMap<String, Integer>();
		// the packages will be ordered by creation date of the first version
		// by default
		
		int groupsCount = 0;
		for (ExportedPackageSummary pack : packages) {
			ExportedPackageSummary latest = latestVersion.get(pack.getGroupUuid());
			if (latest == null) { // the package is added first time, so let's
				                  // provide ordering information
				order.put(pack.getGroupUuid(), groupsCount++);
				latestVersion.put(pack.getGroupUuid(), pack); // update the latest version
			} else if (latest.getVersion() < pack.getVersion()) {
				latestVersion.put(pack.getGroupUuid(), pack); // update the latest version
			}
			if (pack.isPublished() == true) {
				List<Integer> versions = publishedVersions.get(pack.getGroupUuid());
				if (versions == null) {
					versions = new LinkedList<Integer>();
					publishedVersions.put(pack.getGroupUuid(), versions);
				}
				versions.add(pack.getVersion());
			}
		}
		model.addAttribute("packages", latestVersion.values());
		model.addAttribute("publishedVersions", publishedVersions);
		model.addAttribute("order", order);
		model.addAttribute("publishConfigured", MetadataSharing.getInstance().isPublishConfigured());
	}
	
	/**
	 * Gets all packages with the given group and passes to the model (they will be rendered in .jsp
	 * page)
	 */
	@RequestMapping(DETAILS_PATH)
	public String details(String group, Model model) {
		List<ExportedPackageSummary> packages = new ArrayList<ExportedPackageSummary>();
		for (ExportedPackageSummary summary : getService().getAllExportedPackageSummaries()) {
			if (summary.getGroupUuid().equalsIgnoreCase(group)) {
				packages.add(summary);
			}
		}
		Collections.sort(packages, new BeanComparator("version"));
		Collections.reverse(packages);
		if (packages.isEmpty()) {
			return WebUtils.redirect(LIST_PATH);
		}
		else {
			model.addAttribute("packages", packages);
			model.addAttribute("publishUrl", PublishUtils.createAbsolutePublishURL(packages.get(0).getGroupUuid()));
			model.addAttribute("publishConfigured", MetadataSharing.getInstance().isPublishConfigured());
			return DETAILS_PATH;
		}
	}
	
	@RequestMapping(DELETE_PATH)
	public String delete(Integer id, Model model) {
		ExportedPackage pack = MetadataSharing.getService().getExportedPackageById(id);
		if (pack != null) {
			String group = pack.getGroupUuid();
			MetadataSharing.getService().purgeExportedPackage(pack);
			if (MetadataSharing.getService().getLatestExportedPackageByGroup(group) != null) {
				model.addAttribute("group", pack.getGroupUuid());
				return WebUtils.redirect(DETAILS_PATH);
			}
		}
		return WebUtils.redirect(LIST_PATH);
	}
	
	/**
	 * Toggles the "published" field of the package with the given ID and redirects to this
	 * package's summary page
	 */
	@RequestMapping(TOGGLE_PUBLISHED_PATH)
	public String togglePublished(Integer id, Model model) {
		ExportedPackage pack = MetadataSharing.getService().getExportedPackageById(id);
		
		if (MetadataSharing.getInstance().isPublishConfigured()) {
			pack.setPublished(!pack.isPublished());
			MetadataSharing.getService().saveExportedPackage(pack);
			model.addAttribute("group", pack.getGroupUuid());
			return WebUtils.redirect(DETAILS_PATH);
		} else {
			return WebUtils.redirect(LIST_PATH);
		}
	}
	
	@RequestMapping(DOWNLOAD_PATH)
	public ModelAndView download(Integer id, Model model) {
		ExportedPackage pack = MetadataSharing.getService().getExportedPackageById(id);
		model.addAttribute("package", pack);
		return new ModelAndView(downloadPackageView);
	}
	
	@RequestMapping(value = CREATE_PATH, method = RequestMethod.GET)
	public void create(Model model) {
		if (!model.containsAttribute(EXPORTER)) {
			model.addAttribute(EXPORTER, MetadataSharing.getInstance().newPackageExporter());
		}
		model.addAttribute("publishConfigured", MetadataSharing.getInstance().isPublishConfigured());
	}
	
	@RequestMapping(value = UPGRADE_PATH)
	public String upgrade(Integer id, Boolean empty, Model model) throws SerializationException, IOException {
		ExportedPackage exportedPackage = MetadataSharing.getService().getExportedPackageById(id);
		PackageVersioner versioner = null;
		
		if (empty) {
			versioner = MetadataSharing.getInstance().getPackageVersioner(exportedPackage);
		} else {
			SerializedPackage content = exportedPackage.getSerializedPackage();
			ExportedPackage packTmp = MetadataSharing.getInstance().getMetadataSerializer()
			        .deserialize(content.getHeader(), ExportedPackage.class);
			packTmp.setId(exportedPackage.getId());
			versioner = MetadataSharing.getInstance().getPackageVersioner(packTmp);
		}
		
		exportedPackage = versioner.createNewPackageVersion(empty);

omod/src/main/webapp/export/create.jsp
<%@ taglib prefix="springform"
	uri="http://www.springframework.org/tags/form"%>
<%@ include file="../template/localInclude.jsp"%>
<openmrs:require privilege="Share Metadata" otherwise="/login.htm"
	redirect="/module/metadatasharing/export/createPackage.form" />
<%@ include file="../template/jqueryPage.jsp"%>
<%@ include file="../template/localHeader.jsp"%>
<style type="text/css">
.packageDescription {
	width: 400px;
	height: 150px;
}

.error {
	vertical-align: top !important;
}

.grey {
	color: #999;
}
</style>
<h3>
	<spring:message code="metadatasharing.createPackage" />
</h3>

<c:if test="${hasErrors}">
	<div class="warning">
		<span><spring:message code="metadatasharing.error.editPackage" /><br/><br/></span>
	
		<c:if test="${!empty missingClasses}">
			<b><spring:message code="metadatasharing.error.editPackage.missingClasses" /></b>
		</c:if>
		<c:forEach var="missingClass" items="${missingClasses}">
			${missingClass}<br />
		</c:forEach>
		<c:if test="${!empty missingClasses}">
			<br/><br/>
		</c:if>	
			
		<c:if test="${!empty missingItems}">
			<b><spring:message code="metadatasharing.error.editPackage.missingItems" /></b>
		</c:if>
		<c:forEach var="missingType" items="${missingItems}">
			<table width="100%"> 
				<thead> 
					<th><spring:message code="metadatasharing.type" /></th>
					<th><spring:message code="metadatasharing.uuid" /></th>
					<th><spring:message code="metadatasharing.name" /></th>
				</thead>
				<tbody>
					<c:forEach var="missingItem" items="${missingType.value}">
						<tr>
							<td>${missingType.key}</td>
							<td>${missingItem.uuid}</td>
							<td>${missingItem.name}</td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
		</c:forEach>
	</div>
</c:if>

<springform:form modelAttribute="exporter" method="post">
	<fieldset>
		<legend>
			1.
			<spring:message code="metadatasharing.specifyPackage" />
		</legend>
		<p>
		<table>
			<tr>
				<td class="to_upper to_right"><spring:message
						code="metadatasharing.name" />:</td>
				<td><springform:input path="package.name" maxlength="64" /> <springform:errors
						path="package.name" cssClass="error" /></td>
			</tr>
			<tr>

				<td class="to_upper to_right"><spring:message
						code="metadatasharing.description" />:</td>
				<td><springform:textarea path="package.description"
						cssClass="packageDescription" /> <springform:errors
						path="package.description" cssClass="error" /> <br /></td>
			</tr>
		</table>
		</p>
	</fieldset>
	<fieldset>
		<legend>
			2.
			<spring:message code="metadatasharing.packageUpdates" />
		</legend>
		<c:if test="${!publishConfigured}">
			<p>
				<spring:message code="metadatasharing.configure.urlPrefix" />
			</p>
		</c:if>
		<p <c:if test="${!publishConfigured}">class="grey"</c:if>>
			<springform:checkbox path="exportedPackage.published"
				disabled="${!publishConfigured}" />
			<spring:message code="metadatasharing.packageUpdates.description" />
		</p>
	</fieldset>
	<p>
		<input type="submit"
			value="<spring:message code="metadatasharing.next" />" /> <br />
	</p>
</springform:form>
<%@ include file="/WEB-INF/template/footer.jsp"%>

omod/src/main/webapp/export/details.jsp
<%@ include file="../template/localInclude.jsp" %>
<%@ taglib prefix="utils" uri="../taglib/javaScriptPrinter.tld"%>
<openmrs:require privilege="Share Metadata" otherwise="/login.htm" redirect="/module/metadatasharing/export/details.form" />
<%@ include file="../template/jqueryPage.jsp" %> 
<%@ include file="../template/localHeader.jsp" %>
<openmrs:htmlInclude file="${pageContext.request.contextPath}/moduleResources/metadatasharing/css/metadatasharing.css"/> 
<openmrs:htmlInclude file="${pageContext.request.contextPath}/moduleResources/metadatasharing/scripts/packageSummary.js"/>

<script type="text/javascript">
	//Messages definitions
	var $messages = { 
		packageVersions: '<spring:message code="metadatasharing.packageSummary.packageVersions" />',
		latestVersionNotPublished: '<spring:message code="metadatasharing.packageSummary.latestVersionNotPublished" />',
		configure: '<spring:message code="metadatasharing.configure.urlPrefix" />', 
		pleasePublish: '<spring:message code="metadatasharing.packageSummary.pleasePublish" />', 
		confirmDelete: '<spring:message code="metadatasharing.packageSummary.confirmDelete" />', 
		unpublish:'<spring:message code="metadatasharing.packageSummary.unpublish" />',
		publish:'<spring:message code="metadatasharing.packageSummary.publish" />',
		newVersionThisOne: '<spring:message code="metadatasharing.packageSummary.newVersionThisOne" />', 
		downloadZipped: '<spring:message code="metadatasharing.packageSummary.downloadZipped" />', 
		deletePackage: '<spring:message code="metadatasharing.delete" />', 
	}
	
	var $packages = new Array();
	var p = $packages;
	//[ID, VERSION, NAME, DESCRIPTION, DATE_CREATED, PUBLISHED, GROUP]
	<c:forEach var="pack" items="${packages}">
		p.push([<utils:printJavaScript text="${pack.exportedPackageId}"/>,<utils:printJavaScript text="${pack.version}"/>,
		        <utils:printJavaScript text="${pack.name}" asString="true"/>, 
		<utils:printJavaScript text="${pack.description}" asString="true"/>,
		<utils:printJavaScript text="${pack.dateCreated}" asString="true"/>,
		<utils:printJavaScript text="${pack.published}"/>, <utils:printJavaScript text="${pack.groupUuid}" asString="true"/>]);
	</c:forEach>
	var $latestVersionPublished = <utils:printJavaScript text="${packages[0].published}" />;
	var $group = <utils:printJavaScript text="${packages[0].groupUuid}" asString="true"/>; 
	var $publishUrl = <utils:printJavaScript text="${publishUrl}" asString="true"/>; 
	var $publishConfigured = <utils:printJavaScript text="${publishConfigured}"/>; 
	
</script>
<div id="packageSummary">
	<h3><spring:message code="metadatasharing.packageSummary" /></h3>
	<input type="button" value="<spring:message code="metadatasharing.back" />" id="back"/>
	<p id="shareUrl">
		<spring:message code="metadatasharing.packageSummary.shareUrl" />
		<br />
		<input type="text" />
	</p>
	<div class="warning" id="notPublishedWarning" style="display:none;"></div>
    <input type="button" value="<spring:message code="metadatasharing.packageSummary.downloadLatest"  />" id="downloadLatest" class="toolbarButton ui-icon-download"/>
    <input type="button" value="<spring:message code="metadatasharing.packageSummary.newVersionLatest" />" id="latest" class="toolbarButton ui-icon-version"/>
	<input type="button" value="<spring:message code="metadatasharing.packageSummary.newVersionScratch" />" id="scratch" class="toolbarButton ui-icon-scratch"/>
	<table id="packages">
		<thead>
			<tr>
				<th>ID</th>
				<th class="versionColumn"><spring:message code="metadatasharing.version" /></th>
				<th class="nameColumn"><spring:message code="metadatasharing.name" /></th>
				<th class="descriptionColumn"><spring:message code="metadatasharing.description" /></th>
				<th class="dateColumn"><spring:message code="metadatasharing.dateCreated" /></th>
				<th class="publishedColumn"><spring:message code="metadatasharing.published" /></th>
				<th class="actionColumn"><spring:message code="metadatasharing.action" /></th>
			</tr>
		</thead>
	</table>
</div>
<div style="clear:both;"></div>
<%@ include file="/WEB-INF/template/footer.jsp"%>

omod/src/main/webapp/export/edit.jsp
<%@ taglib prefix="springform"
	uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="h" uri="/WEB-INF/view/module/metadatasharing/taglib/openmrsObjectHandler.tld" %>
<%@ include file="../template/localInclude.jsp" %>
<openmrs:require privilege="Share Metadata" otherwise="/login.htm" redirect="/module/metadatasharing/export/editPackage.form" />
<%@ include file="../template/jqueryPage.jsp" %> 
<%@ include file="../template/localHeader.jsp"%>

<script type="text/javascript">
var $j = jQuery.noConflict();
var selectItems;
$j(document).ready(function() {
	$j("#reviewPackageTable").dataTable({
		"bJQueryUI": true,
		"bSort": false,
		"bPaginate": false,
		"sDom": "<t>"
	});
	selectItems = $j('#selectItems').dialog(
			{ autoOpen: false, modal: true, width: '80%', height: $j(window).height()-200,
				resizable: false, draggable: false,
				title: '<spring:message code="metadatasharing.selectItemsToExport" />',
				close: function(event, ui) { $j(this).dialog("option", "buttons", null); } });
	$j('#addMetadata').click(function() {
		selectItems.load('selectItems.form', function() {
			selectItems.dialog("open");
		});
	});
} );
function chooseIndividually(type) {
	if (selectItems != null) {
		selectItems.load('selectItems.form?type=' + encodeURIComponent(type), function() {
			selectItems.dialog("open");
		});
	}
}
function hideShow(elementId) {
	$j("#"+elementId).toggle();
}
</script>

<style>
	.item-details-table {padding: 10px;}
</style>

<div id="selectItems"></div>
<h3><spring:message code="metadatasharing.createPackage" />: ${exporter.getPackage().getName()}</h3>

<springform:form modelAttribute="exporter" action="complete.form" method="post">
	<springform:errors path="package" cssStyle="error" />
	<fieldset>
		<legend>3. <spring:message code="metadatasharing.selectItemsToExport" /></legend>
		<p><input type="button" id="addMetadata" value="<spring:message code="metadatasharing.addMetadataToPackage" />" /></p>
	</fieldset>
	<c:if test="${!empty packageItems.items}">
		<fieldset>
			<legend>4. <spring:message code="metadatasharing.reviewChoice" /></legend>
			<table style="width:100%;">
				<thead>
					<tr><th></th><th><th></th></tr>
				</thead>
				<tbody>
					<c:forEach var="packageItem" items="${packageItems.items}" varStatus="status">
						<tr>
							<td style="vertical-align: top; padding-right: 10px; width:100%;">
								<a href="javascript:hideShow('item-details-${packageItem.key}')">
									${packageItem.key}
									<c:choose>
										<c:when test="${empty packageItems.completeTypesMap[packageItem.key]}">
											(${fn:length(packageItem.value)} selected)
										</c:when>
										<c:otherwise>
											(All ${fn:length(packageItem.value)} selected)
										</c:otherwise>
									</c:choose>
								</a>
								<table class="item-details-table" id="item-details-${packageItem.key}" style="display: none;">
									<tr>
										<td style="padding-top:10px; font-weight: bold;"><spring:message code="metadatasharing.name"/></td>
										<td style="padding-top:10px; font-weight: bold;"><spring:message code="metadatasharing.UUID"/></td>
									</tr>
									<c:forEach var="item" items="${packageItem.value}" varStatus="itemStatus">
										<tr>
											<td style="padding-right: 10px;">
												<c:set var="itemUrl" value="${h:metadataUrl(item.classname, item.uuid)}" />
												<c:choose>
													<c:when test="${empty itemUrl}">
														${item.name}
													</c:when>
													<c:otherwise>
														<a href="${pageContext.request.contextPath}/${itemUrl}" target="__new">${item.name}</a>
													</c:otherwise>
												</c:choose>
											</td>
											<td>${item.uuid}</td>
										</tr>
									</c:forEach>
								</table>
							</td>
							<td style="vertical-align: top; white-space: nowrap;">
								<c:if test="${empty packageItems.completeTypesMap[packageItem.key]}">
								<a href="addAllItems.form?includeRetired=true&type=${packageItem.key}">
								</c:if>
								<spring:message code="metadatasharing.addAll" /><c:if test="${empty packageItems.completeTypesMap[packageItem.key]}"></a></c:if>
								<a href="javascript:chooseIndividually('${packageItem.key}');"><spring:message code="metadatasharing.chooseIndividually" /></a>
								<c:url value="removeAllItems.form?type=${packageItem.key}" var="removeAllUrl" />
								<a href="${removeAllUrl}"><spring:message code="metadatasharing.removeAll" /></a>
							</td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
		</fieldset>
	</c:if>
	<p>
	<c:if test="${!empty packageItems.items}">
		<input type="submit" id="export" value="<spring:message code="metadatasharing.export" />" />
	</c:if>
	<br />
	</p>
</springform:form>
<%@ include file="/WEB-INF/template/footer.jsp"%>

omod/src/main/webapp/export/list.jsp
<%@ include file="../template/localInclude.jsp"%>
<%@ taglib prefix="utils" uri="../taglib/javaScriptPrinter.tld"%>
<%@ taglib prefix="colletions" uri="../taglib/javaScriptCollectionPrinter.tld"%>
<openmrs:require privilege="Share Metadata" otherwise="/login.htm" redirect="/module/metadatasharing/export/list.form" />
<%@ include file="../template/jqueryPage.jsp"%>
<%@ include file="../template/localHeader.jsp"%>
<openmrs:htmlInclude file="${pageContext.request.contextPath}/moduleResources/metadatasharing/css/metadatasharing.css" />
<openmrs:htmlInclude file="${pageContext.request.contextPath}/moduleResources/metadatasharing/scripts/exportList.js"/>

<script type="text/javascript">
	//Messages definitions
	var $messages = { 
		importPackage: '<spring:message code="metadatasharing.importPackage" />',
		createPackage: '<spring:message code="metadatasharing.createPackage" />',
		notPublished: '<spring:message code="metadatasharing.notPublished" />',
		latestVersion: '<spring:message code="metadatasharing.latestVersion" />',
		latestPublishedVersion: '<spring:message code="metadatasharing.latestPublishedVersion" />',
		warning: '<spring:message code="metadatasharing.warning" />',
		downloadPackage: '<spring:message code="metadatasharing.download" />',
		deletePackage: '<spring:message code="metadatasharing.delete" />',
		latestVersionNotPublished: '<spring:message code="metadatasharing.warning.latestVersionNotPublished" />',
		oldPackage: '<spring:message code="metadatasharing.package.old" />'
	};

	var $publishConfigured = <utils:printJavaScript text="${publishConfigured}"/>;
	var $packages = new Array();
	var p = $packages;
	//[ORDER, {name:PACKAGE_NAME, publishedVersions:[1,2,..], latestVersion:LATEST_VERSION, groupUuid:GROUP, id:ID}, DESCRIPTION, DATE_CREATED]
	<c:forEach var="pack" items="${packages}">
		p.push([${order[pack.groupUuid]},{name:<utils:printJavaScript text="${pack.name}" asString="true"/>, 
			publishedVersions:<colletions:printCollectionJavaScript var="${publishedVersions[pack.groupUuid]}" />,
			latestVersion:<utils:printJavaScript text="${pack.version}"/>, groupUuid:<utils:printJavaScript text="${pack.groupUuid}" asString="true"/>,
			id: <utils:printJavaScript text="${pack.exportedPackageId}"/>},
			<utils:printJavaScript text="${pack.description}" asString="true"/>,
			<utils:printJavaScript text="${pack.dateCreated}" asString="true"/>]);
	</c:forEach>  
</script>

<h3><spring:message code="metadatasharing.shareMetadata" /></h3>
<div id="manageMetadataSharing">
	<table id="metadataPackages">
		<thead>
			<tr>
				<th></th>
				<th class="nameColumn"><spring:message code="metadatasharing.name" /></th>
				<th class="descriptionColumn"><spring:message code="metadatasharing.description" /></th>
				<th class="dateColumn"><spring:message code="metadatasharing.modificationDate" /></th>
			</tr>
		</thead>
	</table>
</div>
<%@ include file="/WEB-INF/template/footer.jsp"%>